# jenkins sets this to warn by default
loglevel: info
strictPeerDependencies: true
lockfileIncludeTarballUrl: false

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@com.mgmtp.a12.*/*"

packages:
  - ./*
  - ./documentation/*

catalogs:
  a12Libs:
    "@com.mgmtp.a12.base/base-model-api": "^30.0.1"
    "@com.mgmtp.a12.client/client-application-model-migration": "^17.0.0"
    "@com.mgmtp.a12.client/client-core": "^17.0.0"
    "@com.mgmtp.a12.client/typescript-fsa-redux-5-compat": "^1.0.2"
    "@com.mgmtp.a12.dataservices/dataservices-access": "^39.0.1"
    "@com.mgmtp.a12.dataservices/dataservices-relationship-model-migration": "^39.0.1"
    "@com.mgmtp.a12.expression/expression-core": "^3.0.0"
    "@com.mgmtp.a12.formengine/formengine-core": "^39.0.0"
    "@com.mgmtp.a12.formengine/formengine-model-migration": "^39.0.0"
    "@com.mgmtp.a12.kernel/kernel-core-runtime-api-ts": "^31.1.0"
    "@com.mgmtp.a12.kernel/kernel-md-facade": "^31.1.0"
    "@com.mgmtp.a12.migrationtool/migrationtool-utils": "^3.0.0"
    "@com.mgmtp.a12.migrationtool/migrationtool-core": "^3.0.0"
    "@com.mgmtp.a12.overviewengine/overviewengine-core": "^39.0.0"
    "@com.mgmtp.a12.overviewengine/overviewengine-model-migration": "^39.0.0"
    "@com.mgmtp.a12.utils/utils-collections": "^7.0.1"
    "@com.mgmtp.a12.utils/utils-connector": "^9.0.1"
    "@com.mgmtp.a12.querymodel/querymodel-core": "^0.2.0"
    "@com.mgmtp.a12.utils/utils-localization": "^8.0.1"
    "@com.mgmtp.a12.utils/utils-localization-react": "^8.0.1"
    "@com.mgmtp.a12.utils/utils-logging": "^7.0.1"
    "@com.mgmtp.a12.widgets/widgets-core": "^39.0.1"

  libs:
    "react": "^19.2.6"
    "react-dom": "^19.2.6"
    "react-redux": "^9.2.0"
    "redux": "^5.0.1"
    "redux-saga": "^1.4.2"
    "typed-redux-saga": "^1.5.0"
    "styled-components": "^6.4.3"
    "react-dnd": "^16.0.1"
    "@types/react": "^19.2.6"
    "@types/react-dom": "^19.2.3"
    "typescript": "6.0.2"

  devLibs:
    "@com.mgmtp.a12.devtools/build-tools": "^1.1.2"
    "@playwright/test": "^1.46.1"
    "@com.mgmtp.a12.devtools/eslint-config": "^4.0.0"
    "@com.mgmtp.a12.devtools/prettier-config": "^1.1.1"
    "@com.mgmtp.a12.devtools/tsconfig": "^2.0.1"
    "@types/node": "^22.15.0"
    "@vitest/coverage-v8": "^4.1.8"
    "rimraf": "^6.0.1"
    "vite": "^8.1.0"
    "vitest": "^4.1.8"
