mgmtp.a12.dataservices.attachments.thumbnail.preview.enabled=true
mgmtp.a12.dataservices.attachments.ext.contentstore.embedded.enabled=true
mgmtp.a12.dataservices.attachments.enabled=true
mgmtp.a12.dataservices.attachments.rest-endpoint.enabled=true
