mgmtp.a12.uaa.authentication.types=ANONYMOUS
mgmtp.a12.uaa.authentication.context-path=/api
mgmtp.a12.uaa.authentication.cors.allowedOrigins=*
mgmtp.a12.uaa.authentication.principal.access-rights-resource=classpath:/roles.yaml
mgmtp.a12.uaa.authentication.anonymous.access.urls=/api/**
mgmtp.a12.uaa.authentication.anonymous.roles=anonymous
