server.port=17090

# Profiles
spring.profiles.active=dataservices-actuators,dataservices-rpc,dataservices-embedded_postgres,dataservices-embedded_contentstore,dataservices-uaa,dataservices-cdd_async,content-store,attachments,uaa
# Database
spring.datasources.dataservices.embedded-postgres.path=file:${DB_TEMP_DIR}/db/ds-embedded-postgres
spring.datasources.dataservices.embedded-postgres.port=17091
spring.datasources.contentstore.embedded-postgres.path=file:${DB_TEMP_DIR}/db/cs-embedded-postgres
spring.datasources.contentstore.embedded-postgres.port=17092

# Data (import)
mgmtp.a12.dataservices.initialization.import.models.path=classpath:/models
mgmtp.a12.dataservices.search.index.initialization.mode=rebuild_index

# Actuator
management.endpoint.health.showDetails=always

# Increase maximum page size per query request
mgmtp.a12.dataservices.query.page-request.page-size-limit=9999
# Increase maximum RPC calls per request
mgmtp.a12.dataservices.json-rpc.max-method-calls-per-request=9999
# Increase maximum number of models returned to support dual architectures for the showcase
mgmtp.a12.dataservices.models.list.hardLimit=100

# Full text search
mgmtp.a12.dataservices.search.analysis.fullText.ngrams.enabled=true

# Allow to modify (re-upload) CDM models after starting server
mgmtp.a12.dataservices.cdd.model.modificationAfterInitialization.enabled=true

# Query API
mgmtp.a12.dataservices.query.reindexing.mode=REBUILD_INDEX
mgmtp.a12.dataservices.query.mode=IN_PARALLEL
mgmtp.a12.dataservices.query.impl=JSONB
