/*
 * SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
 *
 * Copyright (c) 2012-2026 mgm technology partners GmbH
 *
 * Dual License
 * ------------
 * This source file is part of the mgm A12 Platform and available under
 * a choice of two different licenses:
 *
 * 1. Open-Source License - EUPL v1.2
 *    You may redistribute and/or modify this file under the terms of the
 *    European Union Public License, version 1.2 - see https://eupl.eu/.
 *
 * 2. Commercial License
 *    Alternatively, you may obtain a commercial license from
 *    mgm technology partners GmbH, that permits use of this software
 *    under different terms (including support and maintenance services).
 *
 *    Please contact a12-license@mgm-tp.com for more information.
 *
 * You must select and comply with exactly one of the above license options.
 *
 * Warranty Disclaimer (applies to either option)
 * ----------------------------------------------
 * THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND,
 * WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE
 * LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
 */

import { it, expect, describe } from "vitest";

import { LOCATION_RUM_ID, runLocationExtraction } from "./location-dualpane-fixture.js";
import {
	formAnnotations,
	formModelReferences,
	findScreenElementById,
	runStaleDetachedRepeatAnnotationExtraction
} from "./annotation-form-fixture.js";

const DETACHED_REPEAT_RUM_ID = "DetachedRepeat-form-binding-DetachedPolicyItemBinding_RuM";

describe("extraction annotation and form reference consistency", () => {
	it("extraction retains relationshipUiReference alongside refreshed canonical annotation", () => {
		const updatedForm = runStaleDetachedRepeatAnnotationExtraction();
		const detachedElement = findScreenElementById(updatedForm, "detached-repeat-items");
		expect(detachedElement).toBeDefined();

		if (detachedElement === undefined) {
			return;
		}

		const annotations = detachedElement.annotations ?? [];
		// Stale annotation is intentionally retained
		expect(annotations.some((a) => a.name === "relationshipUiReference")).toBe(true);
		// New annotation must be present
		const newAnnotation = annotations.find((a) => a.name === "a12-relationship-ui-model-reference");
		expect(newAnnotation).toBeDefined();
		// The new annotation's value must be the generated RuM ID, not the stale fixture value
		expect(newAnnotation?.value).toBe(DETACHED_REPEAT_RUM_ID);
	});

	it("form header modelReferences and annotations agree after extraction", () => {
		// Run Location extraction (non-keepModels for clean state)
		const result = runLocationExtraction(false);

		// bindingConfiguration annotation removed under non-keepModels
		const annotations = formAnnotations(result.updatedForm);
		expect(annotations.some((a) => a.name === "bindingConfiguration")).toBe(false);

		// Form header must have relationship-ui modelRef entries
		const refs = formModelReferences(result.updatedForm);
		const rumRefs = refs.filter((ref) => ref.purpose === "relationship-ui" && ref.modelType === "relationship-ui");
		expect(rumRefs.length).toBeGreaterThan(0);

		// The RuM reference must resolve to the actual added RuM
		const extractedRumIds = result.addedModels
			.filter((m) => m.header.modelType === "relationship-ui")
			.map((m) => m.header.id);
		expect(extractedRumIds.length).toBeGreaterThan(0);

		for (const rumRef of rumRefs) {
			expect(extractedRumIds).toContain(rumRef.reference);
		}
	});

	it("CustomScreenElement references restored where required", () => {
		// Run Location extraction — the BusinessPartner form has a CustomScreenElement
		// `section-10404` bound to the LocationBinding. After extraction, its `reference`
		// field must be set to the LocationBinding RuM ID.
		const result = runLocationExtraction(false);
		const locationCseElement = findScreenElementById(result.updatedForm, "section-10404");
		expect(locationCseElement).toBeDefined();

		if (locationCseElement === undefined) {
			return;
		}

		expect(locationCseElement.type).toBe("CustomScreenElement");
		// The reference must be set to the LocationBinding RuM ID
		expect(locationCseElement.reference).toBe(LOCATION_RUM_ID);
		// After cleanup, bound host element must not carry autogenerated legacy title
		const hostElement = locationCseElement as unknown as Record<string, unknown>;
		expect(hostElement.title).toBeUndefined();
	});
});
