/*
 * SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
 *
 * Copyright (c) 2012-2026 mgm technology partners GmbH
 *
 * Dual License
 * ------------
 * This source file is part of the mgm A12 Platform and available under
 * a choice of two different licenses:
 *
 * 1. Open-Source License - EUPL v1.2
 *    You may redistribute and/or modify this file under the terms of the
 *    European Union Public License, version 1.2 - see https://eupl.eu/.
 *
 * 2. Commercial License
 *    Alternatively, you may obtain a commercial license from
 *    mgm technology partners GmbH, that permits use of this software
 *    under different terms (including support and maintenance services).
 *
 *    Please contact a12-license@mgm-tp.com for more information.
 *
 * You must select and comply with exactly one of the above license options.
 *
 * Warranty Disclaimer (applies to either option)
 * ----------------------------------------------
 * THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND,
 * WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE
 * LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
 */

import { vi } from "vitest";

import type { GenericModel } from "@com.mgmtp.a12.migrationtool/migrationtool-core/types";

import { extractionTransform } from "../../src/internal/steps/RuM/extraction/index.js";
import { DOCUMENT_MODEL_VERSION } from "../../src/internal/steps/RuM/extraction/constants.js";
import { loadFixtureModel, createFixtureContext } from "../internal/test-support/fixture-context-factory.js";
import { buildModelIndex, type ModelIndex, type IndexedModel } from "../internal/test-support/model-index.js";

import { isRecord } from "./fixture-utils.js";

export const LOCATION_SELECTED_OVERVIEW_ID = "LocationLinks-overview";
export const LOCATION_EDIT_OVERVIEW_ID = `${LOCATION_SELECTED_OVERVIEW_ID}-edit`;
export const LOCATION_QUERY_MODEL_ID = `${LOCATION_SELECTED_OVERVIEW_ID}-query`;
export const LOCATION_GENERATED_DOCUMENT_ID = "Location_address____generated";
export const LOCATION_AVAILABLE_OVERVIEW_ID = "Address-overview";

/** RuM ID generated by extraction for the LocationBinding. */
export const LOCATION_RUM_ID = "BusinessPartner-form-binding-LocationBinding_RuM";

export const FIXTURE_PATHS = [
	"shared/relationship-models/Location.json",
	"shared/overview-models/Address-overview.json",
	"shared/overview-models/LocationLinks-overview.json",
	"shared/document-models/Address-document.json",
	"shared/document-models/BusinessPartner-document.json"
] as const;
const FORM_FIXTURE_PATH = "shared/form-models/BusinessPartner-form.json";
const GENERATED_DOCUMENT_TEMPLATE_PATH = "shared/document-models/ClaimLocation_location____generated.json";
const LOCATION_BINDING_NAME = "LocationBinding";

export interface FixtureModel extends IndexedModel {
	readonly header: IndexedModel["header"] & {
		readonly modelVersion?: string;
		readonly annotations?: readonly unknown[];
	};
	readonly content?: unknown;
}

export interface ModelReference {
	readonly purpose?: string;
	readonly modelType?: string;
	readonly reference?: string;
}

export interface ModelAnnotation {
	readonly name?: string;
	readonly value?: string;
}

export interface BindingConfiguration {
	readonly details?: { readonly name?: string; readonly relationshipName?: string };
}

export interface LocationExtractionResult {
	readonly workspaceModels: readonly FixtureModel[];
	readonly addedModels: readonly FixtureModel[];
	readonly updatedForm: FixtureModel;
	readonly rumModel: FixtureModel;
	readonly deletedIds: readonly string[];
	readonly index: ModelIndex<FixtureModel>;
	readonly survivingModels: readonly FixtureModel[];
	readonly findAddedById: (id: string) => FixtureModel | undefined;
	readonly findSurvivingById: (id: string) => FixtureModel | undefined;
}

/** Runs the Location DualPane fixture through extraction with the requested keepModels flag. */
export function runLocationExtraction(keepModels: boolean): LocationExtractionResult {
	const formModel = createLocationOnlyFormModel();
	const generatedDocument = createGeneratedLocationDocument();
	const workspaceModels = [...FIXTURE_PATHS.map(loadFixtureModel), formModel, generatedDocument].map(toFixtureModel);
	const harness = createFixtureContext({ models: workspaceModels, config: { keepModels } });
	const updatedForm = toFixtureModel(
		extractionTransform(formModel, { log: vi.fn(), info: vi.fn(), error: vi.fn() }, harness.context)
	);
	const addedModels = harness.getAddedModels().map(toFixtureModel);
	const deletedIds = harness.getDeletedIds();
	const survivingModels = mergeSurvivingModels(workspaceModels, addedModels, updatedForm, deletedIds);
	const index = buildModelIndex<FixtureModel>(survivingModels.map(withPath));
	const rumModel = requireModel(
		addedModels.find((model) => model.header.modelType === "relationship-ui"),
		"Location relationship-ui"
	);

	return {
		workspaceModels,
		addedModels,
		updatedForm,
		rumModel,
		deletedIds,
		index,
		survivingModels,
		findAddedById: (id) => addedModels.find((model) => model.header.id === id),
		findSurvivingById: (id) => survivingModels.find((model) => model.header.id === id)
	};
}

/**
 * Runs the Location DualPane fixture through extraction with no user config.
 *
 * This exercises the default-absent path: keepModels is omitted entirely from the context,
 * which should behave identically to keepModels: false (non-keepModels).
 */
export function runLocationExtractionConfigAbsent(): LocationExtractionResult {
	const formModel = createLocationOnlyFormModel();
	const generatedDocument = createGeneratedLocationDocument();
	const workspaceModels = [...FIXTURE_PATHS.map(loadFixtureModel), formModel, generatedDocument].map(toFixtureModel);
	const harness = createFixtureContext({ models: workspaceModels });
	const updatedForm = toFixtureModel(
		extractionTransform(formModel, { log: vi.fn(), info: vi.fn(), error: vi.fn() }, harness.context)
	);
	const addedModels = harness.getAddedModels().map(toFixtureModel);
	const deletedIds = harness.getDeletedIds();
	const survivingModels = mergeSurvivingModels(workspaceModels, addedModels, updatedForm, deletedIds);
	const index = buildModelIndex<FixtureModel>(survivingModels.map(withPath));
	const rumModel = requireModel(
		addedModels.find((model) => model.header.modelType === "relationship-ui"),
		"Location relationship-ui"
	);

	return {
		workspaceModels,
		addedModels,
		updatedForm,
		rumModel,
		deletedIds,
		index,
		survivingModels,
		findAddedById: (id) => addedModels.find((model) => model.header.id === id),
		findSurvivingById: (id) => survivingModels.find((model) => model.header.id === id)
	};
}

/** Loads a typed fixture model from the shared fixture tree. */
export function loadTypedFixtureModel(path: string): FixtureModel {
	return toFixtureModel(loadFixtureModel(path));
}

/** Converts a generic fixture to the local test fixture shape. */
export function toFixtureModel(model: GenericModel): FixtureModel {
	return { ...(model as FixtureModel), path: `${(model as FixtureModel).header.id}.json` };
}

/** Returns model header annotations. */
export function annotationsOf(model: FixtureModel): readonly ModelAnnotation[] {
	return (model.header.annotations ?? []).filter(isModelAnnotation);
}

/** Returns model header references. */
export function modelReferencesOf(model: FixtureModel): readonly ModelReference[] {
	return (model.header.modelReferences ?? []).filter(isModelReference);
}

/** Parses bindingConfiguration annotation JSON. */
export function parseBindings(value: string | undefined): readonly BindingConfiguration[] {
	const parsedValue = value === undefined ? [] : (JSON.parse(value) as unknown);

	return Array.isArray(parsedValue) ? parsedValue.filter(isBindingConfiguration) : [];
}

/** Returns header refs matching the requested purpose. */
export function headerRefsWithPurpose(model: FixtureModel, purpose: string): readonly string[] {
	return modelReferencesOf(model).flatMap((reference) =>
		reference.purpose === purpose && typeof reference.reference === "string" ? [reference.reference] : []
	);
}

/** Returns the extracted component object. */
export function getComponent(model: FixtureModel): Record<string, unknown> {
	const component = isRecord(model.content) ? model.content.component : undefined;

	return isRecord(component) ? component : {};
}

/** Returns row action event names from an overview model. */
export function getRowActionEvents(model: FixtureModel): readonly string[] {
	return getRowActions(model).flatMap((action) =>
		isRecord(action) && typeof action.event === "string" ? [action.event] : []
	);
}

/** Returns raw row action entries from an overview model. */
export function getRowActions(model: FixtureModel): readonly unknown[] {
	const rowActionGroup = isRecord(model.content) ? model.content.rowActionGroup : undefined;

	return isRecord(rowActionGroup) && Array.isArray(rowActionGroup.actions) ? rowActionGroup.actions : [];
}

/** Requires an optional value in test setup code. */
export function requireModel<Model>(model: Model | undefined, description: string): Model {
	if (model === undefined) {
		throw new Error(`Expected ${description} to be present`);
	}

	return model;
}

/** Type guard: true if and only if value is a non-null object. Imported from fixture-utils. */
export { isRecord };

export function createLocationOnlyFormModel(): GenericModel {
	const formModel = structuredClone(loadFixtureModel(FORM_FIXTURE_PATH)) as MutableFixtureModel;
	const bindingConfiguration = parseBindings(annotationValue(formModel, "bindingConfiguration")).filter(
		(binding) => binding.details?.name === LOCATION_BINDING_NAME || binding.details?.relationshipName === "Location"
	);

	formModel.header.annotations = annotationsOf(formModel as FixtureModel).map((annotation) =>
		annotation.name === "bindingConfiguration"
			? { ...annotation, value: JSON.stringify(bindingConfiguration) }
			: annotation
	);
	formModel.header.modelReferences = modelReferencesOf(formModel as FixtureModel).filter(
		(reference) => reference.reference !== "PostAddressLinks-overview"
	);

	return formModel as GenericModel;
}

export function createGeneratedLocationDocument(): GenericModel {
	const generatedDocument = structuredClone(loadFixtureModel(GENERATED_DOCUMENT_TEMPLATE_PATH)) as MutableFixtureModel;
	generatedDocument.header.id = LOCATION_GENERATED_DOCUMENT_ID;
	generatedDocument.header.modelVersion = DOCUMENT_MODEL_VERSION;

	if (isRecord(generatedDocument.content) && isRecord(generatedDocument.content.modelInfo)) {
		generatedDocument.content.modelInfo.name = LOCATION_GENERATED_DOCUMENT_ID;
	}

	return generatedDocument as GenericModel;
}

function annotationValue(model: MutableFixtureModel, name: string): string | undefined {
	return model.header.annotations?.find((annotation) => annotation.name === name)?.value;
}

function mergeSurvivingModels(
	initialModels: readonly FixtureModel[],
	addedModels: readonly FixtureModel[],
	updatedForm: FixtureModel,
	deletedIds: readonly string[]
): readonly FixtureModel[] {
	const deletedIdSet = new Set(deletedIds);
	const byId = new Map<string, FixtureModel>();

	for (const model of [...initialModels, ...addedModels, updatedForm]) {
		if (!deletedIdSet.has(model.header.id)) {
			byId.set(model.header.id, model);
		}
	}

	return [...byId.values()];
}

function withPath(model: FixtureModel): FixtureModel {
	return { ...model, path: `${model.header.id}.json` };
}

interface MutableFixtureModel {
	content?: unknown;
	header: {
		id: string;
		modelVersion?: string;
		annotations?: ModelAnnotation[];
		modelReferences?: ModelReference[];
	};
}

function isBindingConfiguration(value: unknown): value is BindingConfiguration {
	return isRecord(value) && (!isRecord(value.details) || typeof value.details.relationshipName === "string");
}

function isModelAnnotation(value: unknown): value is ModelAnnotation {
	return isRecord(value) && (value.name === undefined || typeof value.name === "string");
}

function isModelReference(value: unknown): value is ModelReference {
	return isRecord(value) && (value.reference === undefined || typeof value.reference === "string");
}
