////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.
    
You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS. 
////
== Setup

=== Setup application

To use the CRUD extension in you client application, you only need to register a middleware and some sagas in the application setup as shown below. They can be obtained via the `CRUDFactories`.

[source,typescript,title="Setting up the CRUD extension in a client application"]
----
include::assets/typescript/setup.ts[tags="main"]
----

To make the CRUD Views available, adapt the viewProvider of your application. Then you can refer to the view component names, e.g. "OverviewCRUD", in the VIEW_ADD directives of your application model.

[source,typescript,title="Providing CRUD views"]
----
include::assets/typescript/viewProvider.tsx[tags="main"]
----